### ISSUE TITLE
Update the security overview page to reflect the latest version of ndn-lite

### ISSUE THREAD

**Issue by Zhiyi-Zhang** [named-data-iot/ndn-lite-wiki#1]
The current (6aae1a3)  security overview wiki page is out-of-date.
Since the structure of ndn-lite security has been changed, the wiki page also requires a corresponding update.

**Comment by peurpdapeurp** [comment]
As of the current latest commit of the ndn-lite library (https://github.com/named-data-iot/ndn-lite/commit/c86b38417ff07ed6ad37ea5299d54dcf0cb46710), the ndn-lite-wiki security overview wiki page is up to date (https://github.com/named-data-iot/ndn-lite-wiki/commit/38e806cee6cba5da636528aecec947e7009d72be).
